[application]
name = "grappul"
asset_dir = "assets"
out_dir = "dist"

[web.app]
title = "Grappul - SMITE Guides"


[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
script = []

[web.resource.dev]
script = [] 